Initial products commit
germandilio/project-elara pull request #1
Opened 2023-04-05 15:38 UTC by lemon-doge

todo: fix two hibernate LazyInitializationExceptions in test

2023-04-05 18:48 UTC, germandilio requested changes
В целом ок, но ...
 надо много чего добавить (jpa)
 исправить возвраты контроллера
  я увидел у тебя очень мало логирования
  добавь new line at the and of the files
  добавь @ExceptionHandler aspect для контроллера

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/pom.xml
>          <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
Отступ

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Color.java
> +@Data
Используй подсказку idea, чтобы разбить @Data на аннотации + сгенерированные equals() and hashcode()

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Color.java
> +    private String name;
@Column(length = 64, columnDefinition = "varchar(64)", nullable = false)
пример того что должно быть

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Color.java
> +    private String hex;
@Column(length = 7, columnDefinition = "varchar(7)", nullable = false)
пример того что должно быть

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Feature.java
> +@Data
по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Feature.java
> +    private String name;
по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Feature.java
> +    private String description;
по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Picture.java
> +@Data
по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Color.java
> +@NoArgsConstructor
добавь allargsconstructor

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Feature.java
> +@NoArgsConstructor
добавь allargsconstructor

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Picture.java
> +@NoArgsConstructor
по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Picture.java
> +    private UUID productId;
должно быть private Product product;
с mapping ManyToOne и ReferencedByPrimaryKey, LAZY loading type

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Picture.java
> +    private String uri;
@column по аналогии

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Product.java
> +    private String upc;
все поля ниже проставь varchar(length) и nullable = false везде где это критично

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Product.java
> +    private Boolean deleted = Boolean.FALSE;
@Column(columnDefinition = "boolean default false")

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Product.java
> +@Table(name = "products")
@Where(clause = "deleted = false")

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Product.java
> +
Почитай про optimistic locking with @Version и посмотри нужно ли нам такое здесь

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Sport.java
> +@NoArgsConstructor
Allargsconstructor

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Sport.java
> +    private String name;
column varchar

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/services/ProductsService.java
> +     * the transaction is aborted, runtime exception is thrown
transaction is rolled back and ...

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/services/ProductsService.java
> +        var incorrectIds = new ArrayList<UUID>();
не надо создавать List, просто сделай return false при первой неудачи и позвращай в этом методе boolean и при возврате false кидай исключение

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +        // eсли да то да иначе нет
коменты на анге

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +@RequestMapping("/v1/products/")
обычно здесь последний слеш не ставят и добавляют его потом в начале RequestMapping метода

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +            return new ResponseEntity<>("Products allocated: " + productsService.allocateProducts(requiredProducts), HttpStatus.OK);
в message лучше просто писать products allocated и все, если хочешь вернуть list<Id> то тогда по хорошему отдельную dto надо делать с message и list<id>

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +        // eсли да то да иначе нет
англ комменты

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +            return new ResponseEntity<>("Products deallocated: " + productsService.deallocateProducts(requiredProducts), HttpStatus.OK);
описал выше как сделать

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/services/ProductsService.java
> +        return productsRepository.saveAllAndFlush(updatedProducts).stream().map(Product::getId).collect(Collectors.toList());
сделай пж каждый метод на отдельной строчке

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/test/java/ru/hse/elarateam/ElaraProductsApplicationTests.java
> +        productsRepository.save(Product.builder().name("product1").quantity(10L).build());
поправь все билдеры чтобы каждый метод был на ново строке

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/test/java/ru/hse/elarateam/ElaraProductsApplicationTests.java
> +    @Test
нужно будет переписать тест под новый возвраты сообщений

2023-04-05 18:48 UTC, germandilio commented on Project-Elara/elara-products/src/test/java/ru/hse/elarateam/ElaraProductsApplicationTests.java
> +    public void testAllocateProductsInsufficientQuantity() {
нужно будет переписать тест под новый возвраты сообщений

2023-04-05 19:45 UTC, germandilio commented
Еще везде где lazy инициализация нужно делать @ToString.Exclude

2023-04-06 06:17 UTC, lemon-doge commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/services/ProductsService.java
> +        var incorrectIds = new ArrayList<UUID>();
я хочу все некорректные id вернуть

2023-04-06 06:29 UTC, lemon-doge commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/web/controllers/ProductsController.java
> +        // eсли да то да иначе нет
а я это вообще удалю как сделаем проверку токенов

2023-04-06 06:46 UTC, lemon-doge commented on Project-Elara/elara-products/src/main/java/ru/hse/elarateam/model/Product.java
> +
мы могли бы просто залочить объект полностью 
более высокий уровень транзакции это позволяет по идее

2023-04-06 17:01 UTC, closed without merging