Elara payment initial dev
germandilio/project-elara pull request #8
Opened 2023-04-09 09:32 UTC by lemon-doge

2023-04-09 21:10 UTC, germandilio requested changes

2023-04-09 21:10 UTC, germandilio commented on Project-Elara/elara-payment/src/main/java/ru/hse/elarateam/payment/web/controllers/PaymentController.java
> +    @PostMapping("/register")
можно без /register, просто post на /

2023-04-09 21:10 UTC, germandilio commented on Project-Elara/elara-email/src/main/java/ru/hse/elarateam/email/configs/auth/AuthTokenInterceptor.java
>      public void apply(RequestTemplate requestTemplate) {
здесь по другому будет через feign client

2023-04-11 07:18 UTC, lemon-doge commented on Project-Elara/elara-payment/src/main/java/ru/hse/elarateam/payment/web/controllers/PaymentController.java
> +    @PostMapping("/register")
ок

2023-04-11 08:34 UTC, germandilio approved these changes

2023-04-11 08:34 UTC, merged